In [4]:
import mxnet as mx
from mxnet import nd

## 2.4 data manipulation 

In [6]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [7]:
x = nd.arange(12).reshape((3,4))
y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(y)
y = y + x
id(y) == before

False

In [10]:
z = y.zeros_like()
print(id(z))
z = x + y
print(id(z))

139682661274240
139682661682768


Probs

In [32]:
t = nd.arange(12).reshape((3,3))
z = nd.dot(x, y.T)
temp = z.zeros_like()
z = nd.elemwise_add(temp, t)
print(id(z))
print(id(z))


139682177585744
139682177585744


## 2.4 Linear Algebra

### Tensor

In [33]:
X = nd.arange(24).reshape((2,3,4))
print(X.shape)
print(x)

(2, 3, 4)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>


In [35]:
print(x)
print(nd.sum(x))
print(nd.mean(X))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[66.]
<NDArray 1 @cpu(0)>

[11.5]
<NDArray 1 @cpu(0)>


In [55]:
x = nd.arange(4)
y = nd.ones(4)
print(x, y, nd.dot(x,y))
print(nd.sum(x*y))
print(nd.norm(x))


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[6.]
<NDArray 1 @cpu(0)>

[6.]
<NDArray 1 @cpu(0)>

[3.7416573]
<NDArray 1 @cpu(0)>


### 2.5 Automatic Differentiation

In [48]:
from mxnet import autograd, nd

In [56]:
x = nd.arange(4).reshape((4,1))
print(x)


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>


In [57]:
x.attach_grad()

In [59]:
with autograd.record():
    y= 2 * nd.dot(x.T, x)

print(y)


[[28.]]
<NDArray 1x1 @cpu(0)>


In [60]:
y.backward()

In [61]:
print((x.grad-4*x).norm().asscalar() == 0)
print(x.grad)

True

[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>


In [62]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else: 
        c = 100 * b
    return c

In [65]:
a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    d = f(a)
d.backward()